name: Feature Request
description: Suggest a new feature for the Whoop Alternative project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project would this feature affect?
      options:
        - Firmware (nRF52840)
        - Mobile App (Flutter)
        - Hardware Design
        - Signal Processing
        - BLE Communication
        - Power Management
        - Documentation
        - Build System
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve the project significantly
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Clearly describe how you envision this feature working...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered...

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation ideas
      placeholder: |
        - Implementation approach
        - Hardware requirements
        - Software dependencies
        - Performance considerations
        - Power consumption impact

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Are there examples of this feature in other products?
      placeholder: |
        - Similar features in other devices/apps
        - Research papers or documentation
        - Code examples or APIs

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple addition or modification
        - Medium - Moderate development effort
        - High - Significant development effort
        - Unknown - Not sure about complexity

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: Select all that apply
      options:
        - label: This is a completely new feature
        - label: This is an enhancement to an existing feature
        - label: This affects user interface/experience
        - label: This affects hardware design
        - label: This affects power consumption
        - label: This requires clinical validation
        - label: This has regulatory implications

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Screenshots, diagrams, or additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgments
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: This feature aligns with the project's goals as an open-source wellness device
          required: true
        - label: I understand that feature implementation depends on community contributions and project priorities
          required: true
